# This is the top-level playbook for deploying Bokeh at UNC

- hosts: all
  user: vagrant
  sudo: True
  gather_facts: no
  vars_files:
      - vars/defaults.yml
      - vars/user.yml

  roles:
      - dspace
