- name: dspace | perform fresh install
  command: ant fresh_install chdir={{dspace_source_dir}}/dspace/target/dspace-installer 
  tags: install
  notify:
    - restart tomcat
    - restart apache
- name: dspace | perform update
  command: ant update chdir={{dspace_source_dir}}/dspace/target/dspace-installer
  tags: update 
  when: update
  notify:
    - restart tomcat
    - restart apache                 
